version: '3'

volumes:
  pgdata:

services:
  db:
    container_name: scalaDB
    image: postgres:13
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: scala
      PGGSSENCMODE: disable
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default