CREATE TABLE USERS (
    ID         BIGSERIAL PRIMARY KEY,
    USER_NAME  VARCHAR NOT NULL UNIQUE,
    FIRST_NAME VARCHAR NOT NULL,
    LAST_NAME  VARCHAR NOT NULL,
    EMAIL      VARCHAR NOT NULL,
    PASSWORD   VARCHAR NOT NULL
);

CREATE TABLE TEAM (
    ID         BIGSERIAL PRIMARY KEY,
    NAME       VARCHAR NOT NULL,
    SHIP_DATE  TIMESTAMP NULL,
    STATUS     VARCHAR NOT NULL,
    COMPLETE   BOOLEAN NOT NULL
);